# 20703A2 firmware build 367
# patch entries used: 123 out of 128 elf patches, 96%
CY_PATCH_ENTRIES_BASE=123
# additional patch entries in these libraries:
#   1 in FM25Q04_sflash.a
#   2 in wiced_i2s_test.a
#   2 in boot_lib.a
#   1 in wiced_voice_path.a
#   4 in wiced_audio_sink.a
#   1 in wiced_hal_i2c_lib.a
#   4 in wiced_audio_source.a
#   4 in coex_lib.a
# patch ram used: 60000 out of 65024 bytes, 92%
