# 20703A2 firmware build 422
# patch entries used: 120 out of 128 elf patches, 93%
CY_PATCH_ENTRIES_BASE=120
# additional patch entries in these libraries:
#   1 in wiced_hal_i2c_lib.a
#   4 in wiced_audio_sink.a
#   3 in wiced_voice_path.a
#   1 in FM25Q04_sflash.a
#   1 in wiced_spi_lib.a
#   1 in spiffy_lib.a
#   4 in coex_lib.a
#   5 in wiced_audio_source.a
#   2 in boot_lib.a
#   2 in wiced_i2s_test.a
# patch ram used: 64956 out of 65024 bytes, 99%
